"""Initial 15 tables

Revision ID: 01ea3e7438ca
Revises: 
Create Date: 2026-09-13 22:17:09.021154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ea3e7438ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_api_executions_api_node_id'), table_name='api_executions')
    op.create_index(op.f('ix_api_executions_api_node_id'), 'api_executions', ['api_node_id'], unique=False)
    op.drop_constraint(op.f('api_nodes_slug_key'), 'api_nodes', type_='unique')
    op.drop_index(op.f('idx_api_nodes_owner_id'), table_name='api_nodes')
    op.drop_index(op.f('idx_api_nodes_slug'), table_name='api_nodes')
    op.create_index(op.f('ix_api_nodes_owner_id'), 'api_nodes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_api_nodes_slug'), 'api_nodes', ['slug'], unique=True)
    op.drop_index(op.f('idx_citations_manuscript_id'), table_name='citations')
    op.create_index(op.f('ix_citations_manuscript_id'), 'citations', ['manuscript_id'], unique=False)
    op.drop_index(op.f('idx_code_links_manuscript_id'), table_name='code_links')
    op.drop_index(op.f('idx_code_links_repository_id'), table_name='code_links')
    op.create_index(op.f('ix_code_links_manuscript_id'), 'code_links', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_code_links_repository_id'), 'code_links', ['repository_id'], unique=False)
    op.drop_index(op.f('idx_compliance_checks_manuscript_id'), table_name='compliance_checks')
    op.create_index(op.f('ix_compliance_checks_manuscript_id'), 'compliance_checks', ['manuscript_id'], unique=False)
    op.drop_index(op.f('idx_formulas_manuscript_id'), table_name='formulas')
    op.create_index(op.f('ix_formulas_manuscript_id'), 'formulas', ['manuscript_id'], unique=False)
    op.drop_index(op.f('idx_git_repositories_project_id'), table_name='git_repositories')
    op.create_index(op.f('ix_git_repositories_project_id'), 'git_repositories', ['project_id'], unique=False)
    op.drop_index(op.f('idx_manuscripts_project_id'), table_name='manuscripts')
    op.create_index(op.f('ix_manuscripts_project_id'), 'manuscripts', ['project_id'], unique=False)
    op.drop_index(op.f('idx_publisher_templates_journal_name'), table_name='publisher_templates')
    op.create_index(op.f('ix_publisher_templates_journal_name'), 'publisher_templates', ['journal_name'], unique=False)
    op.drop_index(op.f('idx_references_citation_key'), table_name='references')
    op.drop_index(op.f('idx_references_manuscript_id'), table_name='references')
    op.create_index(op.f('ix_references_citation_key'), 'references', ['citation_key'], unique=False)
    op.create_index(op.f('ix_references_manuscript_id'), 'references', ['manuscript_id'], unique=False)
    op.drop_index(op.f('idx_research_projects_owner_id'), table_name='research_projects')
    op.create_index(op.f('ix_research_projects_owner_id'), 'research_projects', ['owner_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_research_projects_owner_id'), table_name='research_projects')
    op.create_index(op.f('idx_research_projects_owner_id'), 'research_projects', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_references_manuscript_id'), table_name='references')
    op.drop_index(op.f('ix_references_citation_key'), table_name='references')
    op.create_index(op.f('idx_references_manuscript_id'), 'references', ['manuscript_id'], unique=False)
    op.create_index(op.f('idx_references_citation_key'), 'references', ['citation_key'], unique=False)
    op.drop_index(op.f('ix_publisher_templates_journal_name'), table_name='publisher_templates')
    op.create_index(op.f('idx_publisher_templates_journal_name'), 'publisher_templates', ['journal_name'], unique=False)
    op.drop_index(op.f('ix_manuscripts_project_id'), table_name='manuscripts')
    op.create_index(op.f('idx_manuscripts_project_id'), 'manuscripts', ['project_id'], unique=False)
    op.drop_index(op.f('ix_git_repositories_project_id'), table_name='git_repositories')
    op.create_index(op.f('idx_git_repositories_project_id'), 'git_repositories', ['project_id'], unique=False)
    op.drop_index(op.f('ix_formulas_manuscript_id'), table_name='formulas')
    op.create_index(op.f('idx_formulas_manuscript_id'), 'formulas', ['manuscript_id'], unique=False)
    op.drop_index(op.f('ix_compliance_checks_manuscript_id'), table_name='compliance_checks')
    op.create_index(op.f('idx_compliance_checks_manuscript_id'), 'compliance_checks', ['manuscript_id'], unique=False)
    op.drop_index(op.f('ix_code_links_repository_id'), table_name='code_links')
    op.drop_index(op.f('ix_code_links_manuscript_id'), table_name='code_links')
    op.create_index(op.f('idx_code_links_repository_id'), 'code_links', ['repository_id'], unique=False)
    op.create_index(op.f('idx_code_links_manuscript_id'), 'code_links', ['manuscript_id'], unique=False)
    op.drop_index(op.f('ix_citations_manuscript_id'), table_name='citations')
    op.create_index(op.f('idx_citations_manuscript_id'), 'citations', ['manuscript_id'], unique=False)
    op.drop_index(op.f('ix_api_nodes_slug'), table_name='api_nodes')
    op.drop_index(op.f('ix_api_nodes_owner_id'), table_name='api_nodes')
    op.create_index(op.f('idx_api_nodes_slug'), 'api_nodes', ['slug'], unique=False)
    op.create_index(op.f('idx_api_nodes_owner_id'), 'api_nodes', ['owner_id'], unique=False)
    op.create_unique_constraint(op.f('api_nodes_slug_key'), 'api_nodes', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_api_executions_api_node_id'), table_name='api_executions')
    op.create_index(op.f('idx_api_executions_api_node_id'), 'api_executions', ['api_node_id'], unique=False)
    # ### end Alembic commands ###
